packages:
  - packages/*
  - gas

catalog:
  '@base-ui/react': 1.0.0
  '@biomejs/biome': 2.3.4
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@google/clasp': ^3.1.3
  '@slack/web-api': ^7.13.0
  '@standard-schema/spec': ^1.0.0
  '@tailwindcss/vite': 4.1.16
  '@types/google-apps-script': ^2.0.8
  '@types/node': 24.10.1
  '@types/pg': 8.15.6
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@typescript/native-preview': 7.0.0-dev.20251206.1
  '@vitejs/plugin-react': 5.1.2
  babel-plugin-react-compiler: 1.0.0
  better-auth: 1.4.9
  date-fns: ^4.1.0
  dotenv-cli: 11.0.0
  drizzle-kit: 1.0.0-beta.2-86f844e
  drizzle-orm: 1.0.0-beta.2-86f844e
  pg: 8.16.3
  postgres: 3.4.7
  react: 19.2.3
  react-dom: 19.2.3
  react-icons: 'catalog:'
  react-server-dom-webpack: 19.2.3
  rolldown: 1.0.0-beta.59
  tailwindcss: 4.1.17
  tsx: 4.21.0
  typescript: 5.9.3
  vercel: ^50.1.3
  vite-plugin-inspect: ^11.3.3
  waku: 0.27.4
  zod: 4.1.12

catalogMode: strict
