packages:
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  "@base-ui/react": 1.0.0
  "@dnd-kit/core": ^6.3.1
  "@dnd-kit/modifiers": ^9.0.0
  "@dnd-kit/sortable": ^10.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@google/clasp": ^3.1.3
  "@playwright/test": ^1.59.1
  "@rolldown/plugin-babel": ^0.2.2
  "@slack/web-api": ^7.13.0
  "@standard-schema/spec": ^1.0.0
  "@tailwindcss/vite": 4.2.2
  "@tanstack/react-router": ^1.131.35
  "@tanstack/react-start": ^1.131.35
  "@types/google-apps-script": ^2.0.8
  "@types/node": 24.10.1
  "@types/pg": 8.15.6
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/throttle-debounce": ^5.0.2
  "@vitejs/devtools": ^0.1.13
  "@vitejs/plugin-react": 6.0.1
  babel-plugin-react-compiler: 1.0.0
  date-fns: ^4.1.0
  dotenv-cli: 11.0.0
  emulate: ^0.4.1
  fast-fuzzy: ^1.12.0
  knip: ^6.4.0
  mongodb: ^7.5.0
  nitro: 3.0.260415-beta
  oxfmt: ^0.64.0
  oxlint: ^1.79.0
  oxlint-tsgolint: ^7.0.2001
  pg: 8.16.3
  postgres: 3.4.7
  react: 19.2.5
  react-dom: 19.2.5
  react-icons: 5.5.0
  rolldown: 1.0.0-beta.59
  tailwindcss: 4.1.17
  throttle-debounce: ^5.0.2
  tsx: 4.21.0
  typescript: 7.0.2
  vercel: ^50.44.0
  vite: ^8.0.8
  vite-plugin-inspect: ^11.3.3
  zod: 4.1.12

catalogMode: strict

injectWorkspacePackages: true

trustLockfile: true
